#%RAML 1.0 Library

annotationTypes:
  deprecated:
    type: string
    description: Reason why this resource or method is deprecated.
  owner:
    type: string
    description: The team or person responsible for this resource.
  lastModified:
    type: datetime
    description: The last time this resource or method was updated.